version: '3.9'

services:
  go-app:
    container_name: go-app
    image: go-api-tutorial
    build: .
    ports:
      - "8080:8080"
    depends_on:
      go_db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "go_db", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    command: sh -c "sleep 5 && ./main"

  go_db:
    container_name: go_db
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432" 
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata: {}
